services:
  scribeo-web:
    build: .
    command: ["gunicorn", "--bind", ":8000", "backend.wsgi:application"]
    volumes:
      - .:/app
      - media_volume:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - scribeo-db
    env_file:
      - .env

    networks:
      - scribeo-network

  scribeo-db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - scribeo-network

  

volumes:
  db_data:
  media_volume:

networks:
  scribeo-network:
    driver: bridge